# Generated by Django 3.0.6 on 2020-05-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_auto_20200520_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
