# Generated by Django 3.0.6 on 2020-05-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0005_auto_20200525_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='id',
            field=models.IntegerField(max_length=11, primary_key=True, serialize=False),
        ),
    ]
