# Generated by Django 3.0.6 on 2020-05-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0006_auto_20200526_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
