# Generated by Django 3.0.6 on 2020-06-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0007_auto_20200527_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fmhingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingango', models.CharField(max_length=4, verbose_name='Año')),
                ('ingmes', models.CharField(max_length=2, verbose_name='Mes')),
                ('ingcodtipo', models.CharField(max_length=5, verbose_name='Tipo de Inhreso')),
                ('ingGlosa', models.CharField(max_length=70, verbose_name='Glosa')),
                ('ingValor', models.IntegerField(verbose_name='Valor')),
            ],
        ),
    ]
