# Generated by Django 3.0.6 on 2020-06-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0008_fmhingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmhingreso',
            name='ingValor',
            field=models.PositiveIntegerField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='fmhingreso',
            name='ingcodtipo',
            field=models.CharField(max_length=5, verbose_name='Tipo de Ingreso'),
        ),
    ]
