# Generated by Django 3.0.6 on 2020-06-05 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0009_auto_20200604_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmhingreso',
            name='ingValor',
            field=models.IntegerField(verbose_name='Valor'),
        ),
    ]
