# Generated by Django 3.0.6 on 2020-06-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0011_auto_20200612_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmhMovimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movango', models.CharField(max_length=4, verbose_name='Año')),
                ('movmes', models.CharField(max_length=2, verbose_name='Mes')),
                ('movcodtipo', models.CharField(max_length=5, verbose_name='Tipo Mvto.')),
                ('movglosa', models.CharField(max_length=70, verbose_name='Glosa Mvto.')),
                ('movmto', models.IntegerField(verbose_name='Monto')),
            ],
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedango',
            field=models.CharField(max_length=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pedmes',
            field=models.CharField(max_length=2, verbose_name='Mes'),
        ),
    ]
