# Generated by Django 3.0.6 on 2020-06-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0013_auto_20200625_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fmhslddet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdeango', models.CharField(max_length=4, verbose_name='Año')),
                ('sdemes', models.CharField(max_length=2, verbose_name='Mes')),
                ('sdecodsld', models.CharField(max_length=1, verbose_name='Cod. Saldo')),
                ('sdeglosa', models.CharField(max_length=70, verbose_name='Glosa Detalle')),
                ('sdeingresos', models.IntegerField(verbose_name='Ingresos')),
                ('sdeegresos', models.IntegerField(verbose_name='Egresos')),
            ],
        ),
        migrations.CreateModel(
            name='Fmhsldenc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sldango', models.CharField(max_length=4, verbose_name='Año')),
                ('sldmes', models.CharField(max_length=2, verbose_name='Mes')),
                ('sldingresos', models.IntegerField(verbose_name='Ingresos')),
                ('sldegresos', models.IntegerField(verbose_name='Egresos')),
                ('sldsaldo', models.IntegerField(verbose_name='Saldo')),
            ],
        ),
        migrations.AlterField(
            model_name='fmhpago',
            name='pagnumdocu',
            field=models.IntegerField(blank=True, verbose_name='Num. Dcto.'),
        ),
    ]
