# Generated by Django 3.0.6 on 2020-07-04 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0014_auto_20200629_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmhpago',
            name='pagmtopago',
            field=models.PositiveIntegerField(verbose_name='Mto. Pago'),
        ),
        migrations.AlterField(
            model_name='fmhpago',
            name='pagnumdocu',
            field=models.IntegerField(null=True, verbose_name='Num. Dcto.'),
        ),
    ]
