# Generated by Django 3.0.6 on 2020-07-05 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0015_auto_20200703_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmhpago',
            name='Codigo Banco',
            field=models.CharField(default='000', max_length=3),
        ),
    ]
