# Generated by Django 3.0.6 on 2020-07-05 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0016_fmhpago_codigo banco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fmhpago',
            old_name='Codigo Banco',
            new_name='pagCodbco',
        ),
    ]
