# Generated by Django 3.0.6 on 2020-07-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0017_auto_20200704_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmhpago',
            name='pagCodbco',
            field=models.CharField(default='000', max_length=3, verbose_name='Codigo Banco'),
        ),
    ]
