# Generated by Django 3.0.6 on 2020-07-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0018_auto_20200704_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmhpago',
            name='pagCodbco',
            field=models.CharField(max_length=3, null=True, verbose_name='Codigo Banco'),
        ),
    ]
