# Generated by Django 3.0.6 on 2020-07-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0019_auto_20200704_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmhpago',
            name='pagMedpag',
            field=models.CharField(default='', max_length=3, verbose_name='Medio Pago'),
        ),
        migrations.AddField(
            model_name='fmhpago',
            name='pagNumchq',
            field=models.CharField(default='', max_length=10, verbose_name='Nro. Cheque'),
        ),
    ]
