# Generated by Django 3.0.6 on 2020-07-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0022_fmhestadgasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FmhevolGasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolagno', models.CharField(max_length=4, verbose_name='Año')),
                ('evolcepto1', models.FloatField(verbose_name='Financieros')),
                ('evolcepto2', models.FloatField(verbose_name='Fijos')),
                ('evolcepto3', models.FloatField(verbose_name='Autopistas')),
                ('evolcepto4', models.FloatField(verbose_name='Tecnología')),
                ('evolcepto5', models.FloatField(verbose_name='Gastos Médicos')),
                ('evolcepto6', models.FloatField(verbose_name='Colegios')),
                ('evolcepto7', models.FloatField(verbose_name='Supermercado')),
                ('evolcepto8', models.FloatField(verbose_name='Contribuciones')),
                ('evolcepto9', models.FloatField(verbose_name='Otros Gastos')),
            ],
        ),
    ]
